name: CI workflow
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              run: ls -lt
            - name: setup Node.js
              run: apt-get update -y
            - name: install dependencies
              run: npm install
            - name: run test
              run: npm test