name: CI workflow
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              run: ls -lt